services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./tools/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - phpmyadmin
    restart: always
    networks:
      - mysql-phpmyadmin

  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "8080:8080"
    environment:
      MYSQL_ROOT_PASSWORD: 80Qv2r&q3WnO
      MYSQL_DATABASE: rahel
      MYSQL_PASSWORD: 80Qv2r&q3WnO
    networks:
      - mysql-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: 80Qv2r&q3WnO
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin:

volumes:
  db_data:
